// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Admin struct {
	ID        int32
	Name      string
	Email     string
	Role      sql.NullString
	CreatedAt sql.NullTime
}

type Attendance struct {
	ID        int32
	StudentID sql.NullInt32
	CourseID  sql.NullInt32
	CheckIn   sql.NullTime
	CheckOut  sql.NullTime
	Aborted   sql.NullBool
	CreatedAt sql.NullTime
}

type Course struct {
	ID         int32
	Title      string
	Instructor string
	CreatedAt  sql.NullTime
}

type Student struct {
	ID        int32
	Name      string
	Email     string
	CreatedAt sql.NullTime
}
