// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Admin struct {
	ID        int32
	Name      string
	Email     string
	Role      sql.NullString
	CreatedAt sql.NullTime
}

type Attendance struct {
	ID        int32
	StudentID int32
	CourseID  int32
	CheckIn   time.Time
	CheckOut  sql.NullTime
	Status    string
	Aborted   sql.NullBool
	CreatedAt sql.NullTime
}

type Course struct {
	ID         int32
	Title      string
	Instructor string
	CreatedAt  sql.NullTime
}

type Student struct {
	ID        int32
	Name      string
	Email     string
	CreatedAt sql.NullTime
}
