// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: attendance.proto

package attendancepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentRequest) Reset() {
	*x = CreateStudentRequest{}
	mi := &file_attendance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentRequest) ProtoMessage() {}

func (x *CreateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentRequest.ProtoReflect.Descriptor instead.
func (*CreateStudentRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{0}
}

func (x *CreateStudentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStudentRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdateStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStudentRequest) Reset() {
	*x = UpdateStudentRequest{}
	mi := &file_attendance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudentRequest) ProtoMessage() {}

func (x *UpdateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudentRequest.ProtoReflect.Descriptor instead.
func (*UpdateStudentRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateStudentRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStudentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateStudentRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentRequest) Reset() {
	*x = GetStudentRequest{}
	mi := &file_attendance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentRequest) ProtoMessage() {}

func (x *GetStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentRequest.ProtoReflect.Descriptor instead.
func (*GetStudentRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{2}
}

func (x *GetStudentRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentResponse) Reset() {
	*x = StudentResponse{}
	mi := &file_attendance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentResponse) ProtoMessage() {}

func (x *StudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentResponse.ProtoReflect.Descriptor instead.
func (*StudentResponse) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{3}
}

func (x *StudentResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StudentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudentResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *StudentResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type StudentList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*StudentResponse     `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentList) Reset() {
	*x = StudentList{}
	mi := &file_attendance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentList) ProtoMessage() {}

func (x *StudentList) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentList.ProtoReflect.Descriptor instead.
func (*StudentList) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{4}
}

func (x *StudentList) GetStudents() []*StudentResponse {
	if x != nil {
		return x.Students
	}
	return nil
}

type CreateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Instructor    string                 `protobuf:"bytes,2,opt,name=instructor,proto3" json:"instructor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_attendance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCourseRequest) GetInstructor() string {
	if x != nil {
		return x.Instructor
	}
	return ""
}

type UpdateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Instructor    string                 `protobuf:"bytes,3,opt,name=instructor,proto3" json:"instructor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseRequest) Reset() {
	*x = UpdateCourseRequest{}
	mi := &file_attendance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseRequest) ProtoMessage() {}

func (x *UpdateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseRequest.ProtoReflect.Descriptor instead.
func (*UpdateCourseRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCourseRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCourseRequest) GetInstructor() string {
	if x != nil {
		return x.Instructor
	}
	return ""
}

type GetCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseRequest) Reset() {
	*x = GetCourseRequest{}
	mi := &file_attendance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseRequest) ProtoMessage() {}

func (x *GetCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseRequest.ProtoReflect.Descriptor instead.
func (*GetCourseRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{7}
}

func (x *GetCourseRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Instructor    string                 `protobuf:"bytes,3,opt,name=instructor,proto3" json:"instructor,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseResponse) Reset() {
	*x = CourseResponse{}
	mi := &file_attendance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseResponse) ProtoMessage() {}

func (x *CourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseResponse.ProtoReflect.Descriptor instead.
func (*CourseResponse) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{8}
}

func (x *CourseResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CourseResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CourseResponse) GetInstructor() string {
	if x != nil {
		return x.Instructor
	}
	return ""
}

func (x *CourseResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CourseList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*CourseResponse      `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseList) Reset() {
	*x = CourseList{}
	mi := &file_attendance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseList) ProtoMessage() {}

func (x *CourseList) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseList.ProtoReflect.Descriptor instead.
func (*CourseList) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{9}
}

func (x *CourseList) GetCourses() []*CourseResponse {
	if x != nil {
		return x.Courses
	}
	return nil
}

type CreateAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminRequest) Reset() {
	*x = CreateAdminRequest{}
	mi := &file_attendance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminRequest) ProtoMessage() {}

func (x *CreateAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminRequest.ProtoReflect.Descriptor instead.
func (*CreateAdminRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{10}
}

func (x *CreateAdminRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAdminRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetAdminByEmail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminByEmail) Reset() {
	*x = GetAdminByEmail{}
	mi := &file_attendance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminByEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminByEmail) ProtoMessage() {}

func (x *GetAdminByEmail) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminByEmail.ProtoReflect.Descriptor instead.
func (*GetAdminByEmail) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{11}
}

func (x *GetAdminByEmail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AdminLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginRequest) Reset() {
	*x = AdminLoginRequest{}
	mi := &file_attendance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginRequest) ProtoMessage() {}

func (x *AdminLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginRequest.ProtoReflect.Descriptor instead.
func (*AdminLoginRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{12}
}

func (x *AdminLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UpdateAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminRequest) Reset() {
	*x = UpdateAdminRequest{}
	mi := &file_attendance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminRequest) ProtoMessage() {}

func (x *UpdateAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdminRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateAdminRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAdminRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminResponse) Reset() {
	*x = AdminResponse{}
	mi := &file_attendance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResponse) ProtoMessage() {}

func (x *AdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResponse.ProtoReflect.Descriptor instead.
func (*AdminResponse) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{14}
}

func (x *AdminResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AdminList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admins        []*AdminResponse       `protobuf:"bytes,1,rep,name=admins,proto3" json:"admins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminList) Reset() {
	*x = AdminList{}
	mi := &file_attendance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminList) ProtoMessage() {}

func (x *AdminList) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminList.ProtoReflect.Descriptor instead.
func (*AdminList) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{15}
}

func (x *AdminList) GetAdmins() []*AdminResponse {
	if x != nil {
		return x.Admins
	}
	return nil
}

type MarkAttendanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     int32                  `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      int32                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "present", "absent", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAttendanceRequest) Reset() {
	*x = MarkAttendanceRequest{}
	mi := &file_attendance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAttendanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAttendanceRequest) ProtoMessage() {}

func (x *MarkAttendanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAttendanceRequest.ProtoReflect.Descriptor instead.
func (*MarkAttendanceRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{16}
}

func (x *MarkAttendanceRequest) GetStudentId() int32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *MarkAttendanceRequest) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *MarkAttendanceRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AttendanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId     int32                  `protobuf:"varint,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      int32                  `protobuf:"varint,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CheckIn       string                 `protobuf:"bytes,5,opt,name=checkIn,proto3" json:"checkIn,omitempty"`
	Checkout      string                 `protobuf:"bytes,6,opt,name=checkout,proto3" json:"checkout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttendanceResponse) Reset() {
	*x = AttendanceResponse{}
	mi := &file_attendance_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttendanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendanceResponse) ProtoMessage() {}

func (x *AttendanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendanceResponse.ProtoReflect.Descriptor instead.
func (*AttendanceResponse) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{17}
}

func (x *AttendanceResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttendanceResponse) GetStudentId() int32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *AttendanceResponse) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *AttendanceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AttendanceResponse) GetCheckIn() string {
	if x != nil {
		return x.CheckIn
	}
	return ""
}

func (x *AttendanceResponse) GetCheckout() string {
	if x != nil {
		return x.Checkout
	}
	return ""
}

type CreateAttendanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     int32                  `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      int32                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "present", "absent", etc.
	Checkin       string                 `protobuf:"bytes,4,opt,name=checkin,proto3" json:"checkin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAttendanceRequest) Reset() {
	*x = CreateAttendanceRequest{}
	mi := &file_attendance_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttendanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttendanceRequest) ProtoMessage() {}

func (x *CreateAttendanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttendanceRequest.ProtoReflect.Descriptor instead.
func (*CreateAttendanceRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{18}
}

func (x *CreateAttendanceRequest) GetStudentId() int32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *CreateAttendanceRequest) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *CreateAttendanceRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateAttendanceRequest) GetCheckin() string {
	if x != nil {
		return x.Checkin
	}
	return ""
}

type StudentAttendanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     int32                  `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentAttendanceRequest) Reset() {
	*x = StudentAttendanceRequest{}
	mi := &file_attendance_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentAttendanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentAttendanceRequest) ProtoMessage() {}

func (x *StudentAttendanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentAttendanceRequest.ProtoReflect.Descriptor instead.
func (*StudentAttendanceRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{19}
}

func (x *StudentAttendanceRequest) GetStudentId() int32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

type AttendanceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*AttendanceResponse  `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttendanceList) Reset() {
	*x = AttendanceList{}
	mi := &file_attendance_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttendanceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendanceList) ProtoMessage() {}

func (x *AttendanceList) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendanceList.ProtoReflect.Descriptor instead.
func (*AttendanceList) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{20}
}

func (x *AttendanceList) GetRecords() []*AttendanceResponse {
	if x != nil {
		return x.Records
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_attendance_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{21}
}

var File_attendance_proto protoreflect.FileDescriptor

const file_attendance_proto_rawDesc = "" +
	"\n" +
	"\x10attendance.proto\x12\n" +
	"attendance\x1a\x1cgoogle/api/annotations.proto\"@\n" +
	"\x14CreateStudentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"P\n" +
	"\x14UpdateStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"#\n" +
	"\x11GetStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"j\n" +
	"\x0fStudentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"F\n" +
	"\vStudentList\x127\n" +
	"\bstudents\x18\x01 \x03(\v2\x1b.attendance.StudentResponseR\bstudents\"K\n" +
	"\x13CreateCourseRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"instructor\x18\x02 \x01(\tR\n" +
	"instructor\"[\n" +
	"\x13UpdateCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"instructor\x18\x03 \x01(\tR\n" +
	"instructor\"\"\n" +
	"\x10GetCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"u\n" +
	"\x0eCourseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"instructor\x18\x03 \x01(\tR\n" +
	"instructor\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"B\n" +
	"\n" +
	"CourseList\x124\n" +
	"\acourses\x18\x01 \x03(\v2\x1a.attendance.CourseResponseR\acourses\"Z\n" +
	"\x12CreateAdminRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"'\n" +
	"\x0fGetAdminByEmail\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"E\n" +
	"\x11AdminLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"N\n" +
	"\x12UpdateAdminRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"h\n" +
	"\rAdminResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\">\n" +
	"\tAdminList\x121\n" +
	"\x06admins\x18\x01 \x03(\v2\x19.attendance.AdminResponseR\x06admins\"k\n" +
	"\x15MarkAttendanceRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x05R\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x05R\bcourseId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xae\x01\n" +
	"\x12AttendanceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\x05R\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\x05R\bcourseId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\acheckIn\x18\x05 \x01(\tR\acheckIn\x12\x1a\n" +
	"\bcheckout\x18\x06 \x01(\tR\bcheckout\"\x87\x01\n" +
	"\x17CreateAttendanceRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x05R\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x05R\bcourseId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\acheckin\x18\x04 \x01(\tR\acheckin\"9\n" +
	"\x18StudentAttendanceRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x05R\tstudentId\"J\n" +
	"\x0eAttendanceList\x128\n" +
	"\arecords\x18\x01 \x03(\v2\x1e.attendance.AttendanceResponseR\arecords\"\a\n" +
	"\x05Empty2\xb4\x02\n" +
	"\x0eStudentService\x12g\n" +
	"\rCreateStudent\x12 .attendance.CreateStudentRequest\x1a\x1b.attendance.StudentResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/students\x12g\n" +
	"\x0eGetStudentByID\x12\x1d.attendance.GetStudentRequest\x1a\x1b.attendance.StudentResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/students/{id}\x12P\n" +
	"\fListStudents\x12\x11.attendance.Empty\x1a\x17.attendance.StudentList\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/students2\xc3\x01\n" +
	"\rCourseService\x12c\n" +
	"\fCreateCourse\x12\x1f.attendance.CreateCourseRequest\x1a\x1a.attendance.CourseResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/courses\x12M\n" +
	"\vListCourses\x12\x11.attendance.Empty\x1a\x16.attendance.CourseList\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/courses2\xd4\x01\n" +
	"\fAdminService\x12_\n" +
	"\vCreateAdmin\x12\x1e.attendance.CreateAdminRequest\x1a\x19.attendance.AdminResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/admins\x12c\n" +
	"\n" +
	"LoginAdmin\x12\x1d.attendance.AdminLoginRequest\x1a\x19.attendance.AdminResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/admins/login2\x86\x02\n" +
	"\x11AttendanceService\x12n\n" +
	"\x0eMarkAttendance\x12!.attendance.MarkAttendanceRequest\x1a\x1e.attendance.AttendanceResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/attendance\x12\x80\x01\n" +
	"\x17GetAttendanceForStudent\x12$.attendance.StudentAttendanceRequest\x1a\x1a.attendance.AttendanceList\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/attendance/{student_id}B\x1fZ\x1dinternal/service/attendancepbb\x06proto3"

var (
	file_attendance_proto_rawDescOnce sync.Once
	file_attendance_proto_rawDescData []byte
)

func file_attendance_proto_rawDescGZIP() []byte {
	file_attendance_proto_rawDescOnce.Do(func() {
		file_attendance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attendance_proto_rawDesc), len(file_attendance_proto_rawDesc)))
	})
	return file_attendance_proto_rawDescData
}

var file_attendance_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_attendance_proto_goTypes = []any{
	(*CreateStudentRequest)(nil),     // 0: attendance.CreateStudentRequest
	(*UpdateStudentRequest)(nil),     // 1: attendance.UpdateStudentRequest
	(*GetStudentRequest)(nil),        // 2: attendance.GetStudentRequest
	(*StudentResponse)(nil),          // 3: attendance.StudentResponse
	(*StudentList)(nil),              // 4: attendance.StudentList
	(*CreateCourseRequest)(nil),      // 5: attendance.CreateCourseRequest
	(*UpdateCourseRequest)(nil),      // 6: attendance.UpdateCourseRequest
	(*GetCourseRequest)(nil),         // 7: attendance.GetCourseRequest
	(*CourseResponse)(nil),           // 8: attendance.CourseResponse
	(*CourseList)(nil),               // 9: attendance.CourseList
	(*CreateAdminRequest)(nil),       // 10: attendance.CreateAdminRequest
	(*GetAdminByEmail)(nil),          // 11: attendance.GetAdminByEmail
	(*AdminLoginRequest)(nil),        // 12: attendance.AdminLoginRequest
	(*UpdateAdminRequest)(nil),       // 13: attendance.UpdateAdminRequest
	(*AdminResponse)(nil),            // 14: attendance.AdminResponse
	(*AdminList)(nil),                // 15: attendance.AdminList
	(*MarkAttendanceRequest)(nil),    // 16: attendance.MarkAttendanceRequest
	(*AttendanceResponse)(nil),       // 17: attendance.AttendanceResponse
	(*CreateAttendanceRequest)(nil),  // 18: attendance.CreateAttendanceRequest
	(*StudentAttendanceRequest)(nil), // 19: attendance.StudentAttendanceRequest
	(*AttendanceList)(nil),           // 20: attendance.AttendanceList
	(*Empty)(nil),                    // 21: attendance.Empty
}
var file_attendance_proto_depIdxs = []int32{
	3,  // 0: attendance.StudentList.students:type_name -> attendance.StudentResponse
	8,  // 1: attendance.CourseList.courses:type_name -> attendance.CourseResponse
	14, // 2: attendance.AdminList.admins:type_name -> attendance.AdminResponse
	17, // 3: attendance.AttendanceList.records:type_name -> attendance.AttendanceResponse
	0,  // 4: attendance.StudentService.CreateStudent:input_type -> attendance.CreateStudentRequest
	2,  // 5: attendance.StudentService.GetStudentByID:input_type -> attendance.GetStudentRequest
	21, // 6: attendance.StudentService.ListStudents:input_type -> attendance.Empty
	5,  // 7: attendance.CourseService.CreateCourse:input_type -> attendance.CreateCourseRequest
	21, // 8: attendance.CourseService.ListCourses:input_type -> attendance.Empty
	10, // 9: attendance.AdminService.CreateAdmin:input_type -> attendance.CreateAdminRequest
	12, // 10: attendance.AdminService.LoginAdmin:input_type -> attendance.AdminLoginRequest
	16, // 11: attendance.AttendanceService.MarkAttendance:input_type -> attendance.MarkAttendanceRequest
	19, // 12: attendance.AttendanceService.GetAttendanceForStudent:input_type -> attendance.StudentAttendanceRequest
	3,  // 13: attendance.StudentService.CreateStudent:output_type -> attendance.StudentResponse
	3,  // 14: attendance.StudentService.GetStudentByID:output_type -> attendance.StudentResponse
	4,  // 15: attendance.StudentService.ListStudents:output_type -> attendance.StudentList
	8,  // 16: attendance.CourseService.CreateCourse:output_type -> attendance.CourseResponse
	9,  // 17: attendance.CourseService.ListCourses:output_type -> attendance.CourseList
	14, // 18: attendance.AdminService.CreateAdmin:output_type -> attendance.AdminResponse
	14, // 19: attendance.AdminService.LoginAdmin:output_type -> attendance.AdminResponse
	17, // 20: attendance.AttendanceService.MarkAttendance:output_type -> attendance.AttendanceResponse
	20, // 21: attendance.AttendanceService.GetAttendanceForStudent:output_type -> attendance.AttendanceList
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_attendance_proto_init() }
func file_attendance_proto_init() {
	if File_attendance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attendance_proto_rawDesc), len(file_attendance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_attendance_proto_goTypes,
		DependencyIndexes: file_attendance_proto_depIdxs,
		MessageInfos:      file_attendance_proto_msgTypes,
	}.Build()
	File_attendance_proto = out.File
	file_attendance_proto_goTypes = nil
	file_attendance_proto_depIdxs = nil
}
