// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: attendance.proto

package attendancepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentRequest) Reset() {
	*x = CreateStudentRequest{}
	mi := &file_attendance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentRequest) ProtoMessage() {}

func (x *CreateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentRequest.ProtoReflect.Descriptor instead.
func (*CreateStudentRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{0}
}

func (x *CreateStudentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStudentRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentRequest) Reset() {
	*x = GetStudentRequest{}
	mi := &file_attendance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentRequest) ProtoMessage() {}

func (x *GetStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentRequest.ProtoReflect.Descriptor instead.
func (*GetStudentRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{1}
}

func (x *GetStudentRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentResponse) Reset() {
	*x = StudentResponse{}
	mi := &file_attendance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentResponse) ProtoMessage() {}

func (x *StudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentResponse.ProtoReflect.Descriptor instead.
func (*StudentResponse) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{2}
}

func (x *StudentResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StudentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudentResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *StudentResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type StudentList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*StudentResponse     `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentList) Reset() {
	*x = StudentList{}
	mi := &file_attendance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentList) ProtoMessage() {}

func (x *StudentList) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentList.ProtoReflect.Descriptor instead.
func (*StudentList) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{3}
}

func (x *StudentList) GetStudents() []*StudentResponse {
	if x != nil {
		return x.Students
	}
	return nil
}

type CreateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_attendance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseResponse) Reset() {
	*x = CourseResponse{}
	mi := &file_attendance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseResponse) ProtoMessage() {}

func (x *CourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseResponse.ProtoReflect.Descriptor instead.
func (*CourseResponse) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{5}
}

func (x *CourseResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CourseResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CourseResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CourseList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*CourseResponse      `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseList) Reset() {
	*x = CourseList{}
	mi := &file_attendance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseList) ProtoMessage() {}

func (x *CourseList) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseList.ProtoReflect.Descriptor instead.
func (*CourseList) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{6}
}

func (x *CourseList) GetCourses() []*CourseResponse {
	if x != nil {
		return x.Courses
	}
	return nil
}

type CreateAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminRequest) Reset() {
	*x = CreateAdminRequest{}
	mi := &file_attendance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminRequest) ProtoMessage() {}

func (x *CreateAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminRequest.ProtoReflect.Descriptor instead.
func (*CreateAdminRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAdminRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAdminRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AdminLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginRequest) Reset() {
	*x = AdminLoginRequest{}
	mi := &file_attendance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginRequest) ProtoMessage() {}

func (x *AdminLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginRequest.ProtoReflect.Descriptor instead.
func (*AdminLoginRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{8}
}

func (x *AdminLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminResponse) Reset() {
	*x = AdminResponse{}
	mi := &file_attendance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResponse) ProtoMessage() {}

func (x *AdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResponse.ProtoReflect.Descriptor instead.
func (*AdminResponse) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{9}
}

func (x *AdminResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type MarkAttendanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     int32                  `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      int32                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "present", "absent", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAttendanceRequest) Reset() {
	*x = MarkAttendanceRequest{}
	mi := &file_attendance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAttendanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAttendanceRequest) ProtoMessage() {}

func (x *MarkAttendanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAttendanceRequest.ProtoReflect.Descriptor instead.
func (*MarkAttendanceRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{10}
}

func (x *MarkAttendanceRequest) GetStudentId() int32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *MarkAttendanceRequest) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *MarkAttendanceRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AttendanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId     int32                  `protobuf:"varint,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      int32                  `protobuf:"varint,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttendanceResponse) Reset() {
	*x = AttendanceResponse{}
	mi := &file_attendance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttendanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendanceResponse) ProtoMessage() {}

func (x *AttendanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendanceResponse.ProtoReflect.Descriptor instead.
func (*AttendanceResponse) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{11}
}

func (x *AttendanceResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttendanceResponse) GetStudentId() int32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *AttendanceResponse) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *AttendanceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AttendanceResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type StudentAttendanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     int32                  `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentAttendanceRequest) Reset() {
	*x = StudentAttendanceRequest{}
	mi := &file_attendance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentAttendanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentAttendanceRequest) ProtoMessage() {}

func (x *StudentAttendanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentAttendanceRequest.ProtoReflect.Descriptor instead.
func (*StudentAttendanceRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{12}
}

func (x *StudentAttendanceRequest) GetStudentId() int32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

type AttendanceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*AttendanceResponse  `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttendanceList) Reset() {
	*x = AttendanceList{}
	mi := &file_attendance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttendanceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendanceList) ProtoMessage() {}

func (x *AttendanceList) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendanceList.ProtoReflect.Descriptor instead.
func (*AttendanceList) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{13}
}

func (x *AttendanceList) GetRecords() []*AttendanceResponse {
	if x != nil {
		return x.Records
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_attendance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{14}
}

var File_attendance_proto protoreflect.FileDescriptor

const file_attendance_proto_rawDesc = "" +
	"\n" +
	"\x10attendance.proto\x12\n" +
	"attendance\x1a\x1cgoogle/api/annotations.proto\"@\n" +
	"\x14CreateStudentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"#\n" +
	"\x11GetStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"j\n" +
	"\x0fStudentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"F\n" +
	"\vStudentList\x127\n" +
	"\bstudents\x18\x01 \x03(\v2\x1b.attendance.StudentResponseR\bstudents\"M\n" +
	"\x13CreateCourseRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"X\n" +
	"\x0eCourseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"B\n" +
	"\n" +
	"CourseList\x124\n" +
	"\acourses\x18\x01 \x03(\v2\x1a.attendance.CourseResponseR\acourses\"Z\n" +
	"\x12CreateAdminRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"E\n" +
	"\x11AdminLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"I\n" +
	"\rAdminResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"k\n" +
	"\x15MarkAttendanceRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x05R\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x05R\bcourseId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x96\x01\n" +
	"\x12AttendanceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\x05R\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\x05R\bcourseId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"9\n" +
	"\x18StudentAttendanceRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x05R\tstudentId\"J\n" +
	"\x0eAttendanceList\x128\n" +
	"\arecords\x18\x01 \x03(\v2\x1e.attendance.AttendanceResponseR\arecords\"\a\n" +
	"\x05Empty2\xb4\x02\n" +
	"\x0eStudentService\x12g\n" +
	"\rCreateStudent\x12 .attendance.CreateStudentRequest\x1a\x1b.attendance.StudentResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/students\x12g\n" +
	"\x0eGetStudentByID\x12\x1d.attendance.GetStudentRequest\x1a\x1b.attendance.StudentResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/students/{id}\x12P\n" +
	"\fListStudents\x12\x11.attendance.Empty\x1a\x17.attendance.StudentList\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/students2\xc3\x01\n" +
	"\rCourseService\x12c\n" +
	"\fCreateCourse\x12\x1f.attendance.CreateCourseRequest\x1a\x1a.attendance.CourseResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/courses\x12M\n" +
	"\vListCourses\x12\x11.attendance.Empty\x1a\x16.attendance.CourseList\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/courses2\xd4\x01\n" +
	"\fAdminService\x12_\n" +
	"\vCreateAdmin\x12\x1e.attendance.CreateAdminRequest\x1a\x19.attendance.AdminResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/admins\x12c\n" +
	"\n" +
	"LoginAdmin\x12\x1d.attendance.AdminLoginRequest\x1a\x19.attendance.AdminResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/admins/login2\x86\x02\n" +
	"\x11AttendanceService\x12n\n" +
	"\x0eMarkAttendance\x12!.attendance.MarkAttendanceRequest\x1a\x1e.attendance.AttendanceResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/attendance\x12\x80\x01\n" +
	"\x17GetAttendanceForStudent\x12$.attendance.StudentAttendanceRequest\x1a\x1a.attendance.AttendanceList\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/attendance/{student_id}B\x1fZ\x1dinternal/service/attendancepbb\x06proto3"

var (
	file_attendance_proto_rawDescOnce sync.Once
	file_attendance_proto_rawDescData []byte
)

func file_attendance_proto_rawDescGZIP() []byte {
	file_attendance_proto_rawDescOnce.Do(func() {
		file_attendance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attendance_proto_rawDesc), len(file_attendance_proto_rawDesc)))
	})
	return file_attendance_proto_rawDescData
}

var file_attendance_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_attendance_proto_goTypes = []any{
	(*CreateStudentRequest)(nil),     // 0: attendance.CreateStudentRequest
	(*GetStudentRequest)(nil),        // 1: attendance.GetStudentRequest
	(*StudentResponse)(nil),          // 2: attendance.StudentResponse
	(*StudentList)(nil),              // 3: attendance.StudentList
	(*CreateCourseRequest)(nil),      // 4: attendance.CreateCourseRequest
	(*CourseResponse)(nil),           // 5: attendance.CourseResponse
	(*CourseList)(nil),               // 6: attendance.CourseList
	(*CreateAdminRequest)(nil),       // 7: attendance.CreateAdminRequest
	(*AdminLoginRequest)(nil),        // 8: attendance.AdminLoginRequest
	(*AdminResponse)(nil),            // 9: attendance.AdminResponse
	(*MarkAttendanceRequest)(nil),    // 10: attendance.MarkAttendanceRequest
	(*AttendanceResponse)(nil),       // 11: attendance.AttendanceResponse
	(*StudentAttendanceRequest)(nil), // 12: attendance.StudentAttendanceRequest
	(*AttendanceList)(nil),           // 13: attendance.AttendanceList
	(*Empty)(nil),                    // 14: attendance.Empty
}
var file_attendance_proto_depIdxs = []int32{
	2,  // 0: attendance.StudentList.students:type_name -> attendance.StudentResponse
	5,  // 1: attendance.CourseList.courses:type_name -> attendance.CourseResponse
	11, // 2: attendance.AttendanceList.records:type_name -> attendance.AttendanceResponse
	0,  // 3: attendance.StudentService.CreateStudent:input_type -> attendance.CreateStudentRequest
	1,  // 4: attendance.StudentService.GetStudentByID:input_type -> attendance.GetStudentRequest
	14, // 5: attendance.StudentService.ListStudents:input_type -> attendance.Empty
	4,  // 6: attendance.CourseService.CreateCourse:input_type -> attendance.CreateCourseRequest
	14, // 7: attendance.CourseService.ListCourses:input_type -> attendance.Empty
	7,  // 8: attendance.AdminService.CreateAdmin:input_type -> attendance.CreateAdminRequest
	8,  // 9: attendance.AdminService.LoginAdmin:input_type -> attendance.AdminLoginRequest
	10, // 10: attendance.AttendanceService.MarkAttendance:input_type -> attendance.MarkAttendanceRequest
	12, // 11: attendance.AttendanceService.GetAttendanceForStudent:input_type -> attendance.StudentAttendanceRequest
	2,  // 12: attendance.StudentService.CreateStudent:output_type -> attendance.StudentResponse
	2,  // 13: attendance.StudentService.GetStudentByID:output_type -> attendance.StudentResponse
	3,  // 14: attendance.StudentService.ListStudents:output_type -> attendance.StudentList
	5,  // 15: attendance.CourseService.CreateCourse:output_type -> attendance.CourseResponse
	6,  // 16: attendance.CourseService.ListCourses:output_type -> attendance.CourseList
	9,  // 17: attendance.AdminService.CreateAdmin:output_type -> attendance.AdminResponse
	9,  // 18: attendance.AdminService.LoginAdmin:output_type -> attendance.AdminResponse
	11, // 19: attendance.AttendanceService.MarkAttendance:output_type -> attendance.AttendanceResponse
	13, // 20: attendance.AttendanceService.GetAttendanceForStudent:output_type -> attendance.AttendanceList
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_attendance_proto_init() }
func file_attendance_proto_init() {
	if File_attendance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attendance_proto_rawDesc), len(file_attendance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_attendance_proto_goTypes,
		DependencyIndexes: file_attendance_proto_depIdxs,
		MessageInfos:      file_attendance_proto_msgTypes,
	}.Build()
	File_attendance_proto = out.File
	file_attendance_proto_goTypes = nil
	file_attendance_proto_depIdxs = nil
}
